module CrystalPlay
  module PluginHelpers
    # DistributionFacts - the per-distro DISPLAY-NAME logic real Ansible's
    # DistributionFactCollector applies on top of the generic
    # /etc/os-release facts, ported from its own
    # `module_utils/facts/system/distribution.py`. Pure string logic, no
    # I/O, so it is unit-testable against a corpus of real os-release
    # files - see distribution_facts_spec.cr, whose expectations were
    # generated by running the REAL Python parser over that same corpus
    # rather than written by hand.
    module DistributionFacts
      # Real Ansible's own `parse_distribution_file_Debian`, ported branch
      # for branch and IN ITS ORDER - the order is load-bearing, since
      # several of these substrings co-occur in one /etc/os-release (LMDE's
      # own file mentions linuxmint.com, Kali's mentions Debian), and real
      # Ansible's first matching branch wins.
      #
      # Real Ansible reports a per-distro DISPLAY NAME here, not the
      # capitalized os-release ID this engine used to emit: on LMDE 7 it
      # says "Linux Mint Debian Edition" where this said "Linuxmint", and
      # on Raspbian it says "Debian" where this said "Raspbian". A role
      # gating on `ansible_distribution == "Linux Mint"`, or keying a vars
      # file off it, took the wrong branch on every derivative.
      #
      # Returns the facts to OVERRIDE (never mutating the caller's own
      # differently-typed fact hash), or nil for real Ansible's own
      # `return False` - no branch matched, and the generic os-release
      # name the caller already computed stands.
      #
      # Several branches deliberately reproduce quirks of the Python
      # original rather than "fixing" them, because parity is the goal
      # and a role may already depend on them: the release regexes use a
      # negated character class with no MULTILINE anchor, so `[^"]+` runs
      # PAST the end of its own line (real Ansible's Deepin
      # distribution_release is literally "apricot\nID=Deepin\n
      # ID_LIKE=debian\n"). Crystal's regex engine behaves the same way
      # here, which the corpus differential confirms rather than assumes.
      def self.refine_debian(data : String) : Hash(String, String)?
        overrides = Hash(String, String).new

        if data.includes?("Debian") || data.includes?("Raspbian")
          if release = data.match(/PRETTY_NAME=[^(]+ \(?([^)]+?)\)/)
            overrides["ansible_distribution_release"] = release[1]
          end
          overrides["ansible_distribution"] = "Debian"
          return overrides
        end

        if data.includes?("Ubuntu")
          overrides["ansible_distribution"] = "Ubuntu"
          return overrides
        end

        if data.includes?("SteamOS")
          overrides["ansible_distribution"] = "SteamOS"
          return overrides
        end

        if data.includes?("Kali") || data.includes?("Parrot")
          if release = data.match(/DISTRIB_RELEASE=(.*)/)
            overrides["ansible_distribution_release"] = release[1]
          end
          overrides["ansible_distribution"] = data.includes?("Kali") ? "Kali" : "Parrot"
          return overrides
        end

        if data.includes?("Devuan")
          if release = data.match(/PRETTY_NAME="?[^("]+ \(?([^) "]+)\)?/)
            overrides["ansible_distribution_release"] = release[1]
          end
          if version = data.match(/VERSION_ID="(.*)"/)
            overrides["ansible_distribution_version"] = version[1]
            overrides["ansible_distribution_major_version"] = version[1]
          end
          overrides["ansible_distribution"] = "Devuan"
          return overrides
        end

        if data.includes?("Cumulus")
          if version = data.match(/VERSION_ID=(.*)/)
            overrides["ansible_distribution_version"] = version[1]
            overrides["ansible_distribution_major_version"] = version[1].split(".").first
          end
          if release = data.match(/VERSION="(.*)"/)
            overrides["ansible_distribution_release"] = release[1]
          end
          overrides["ansible_distribution"] = "Cumulus Linux"
          return overrides
        end

        if data.includes?("Mint")
          if version = data.match(/VERSION_ID="(.*)"/)
            overrides["ansible_distribution_version"] = version[1]
            overrides["ansible_distribution_major_version"] = version[1].split(".").first
          end
          overrides["ansible_distribution"] = "Linux Mint"
          return overrides
        end

        if data.includes?("UOS") || data.includes?("Uos") || data.includes?("uos")
          if release = data.match(/VERSION_CODENAME="?([^"]+)"?/)
            overrides["ansible_distribution_release"] = release[1]
          end
          if version = data.match(/VERSION_ID="(.*)"/)
            overrides["ansible_distribution_version"] = version[1]
            overrides["ansible_distribution_major_version"] = version[1].split(".").first
          end
          overrides["ansible_distribution"] = "Uos"
          return overrides
        end

        if data.includes?("Deepin") || data.includes?("deepin")
          if release = data.match(/VERSION_CODENAME="?([^"]+)"?/)
            overrides["ansible_distribution_release"] = release[1]
          end
          if version = data.match(/VERSION_ID="(.*)"/)
            overrides["ansible_distribution_version"] = version[1]
            overrides["ansible_distribution_major_version"] = version[1].split(".").first
          end
          overrides["ansible_distribution"] = "Deepin"
          return overrides
        end

        if data.includes?("LMDE")
          overrides["ansible_distribution"] = "Linux Mint Debian Edition"
          return overrides
        end

        nil
      end

      # Names and groupings taken from real Ansible's own OS_FAMILY_MAP
      # (module_utils/facts/system/distribution.py), so the display names
      # #refine_debian now produces ("Linux Mint Debian Edition",
      # "Cumulus Linux", "Devuan", ...) still map to the right family -
      # none of them is an os-release ID, so they would otherwise fall
      # through to ID_LIKE, or to the distribution name itself.
      def self.family_for(name : String) : String?
        case name
        when "Ubuntu", "Debian", "Linuxmint", "Raspbian", "Neon", "KDE neon",
             "Linux Mint", "SteamOS", "Devuan", "Kali", "Cumulus Linux",
             "Pop!_OS", "Parrot", "Pardus GNU/Linux", "Uos", "Deepin", "OSMC",
             "Linux Mint Debian Edition"
          "Debian"
        when "CentOS", "RedHat", "RHEL", "Fedora", "Rocky", "AlmaLinux",
             "Amazon", "Amzn", "Oracle", "OracleLinux", "Scientific",
             "CloudLinux", "Virtuozzo", "XenServer", "Alibaba", "EulerOS",
             "openEuler", "TencentOS", "EuroLinux", "MIRACLE"
          "RedHat"
        when "Arch", "Archlinux", "Antergos", "Manjaro"
          "Archlinux"
        when "SUSE", "Opensuse", "Suse", "SuSE", "SLES", "SLED", "openSUSE",
             "openSUSE Tumbleweed", "openSUSE Leap", "SUSE_LINUX"
          "Suse"
        when "Alpine"
          "Alpine"
        when "Gentoo", "Funtoo"
          "Gentoo"
        when "Mandrake", "Mandriva"
          "Mandrake"
        when "Slackware"
          "Slackware"
        when "Altlinux"
          "Altlinux"
        else
          nil
        end
      end
    end
  end
end
