FROM docker.io/library/ubuntu:22.04
RUN apt-get update && apt-get install -y openssh-server python3 rsync && \
    mkdir -p /run/sshd /root/.ssh && chmod 700 /root/.ssh
COPY key.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys && \
    sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
CMD ["/usr/sbin/sshd","-D","-e"]
