require "../spec_helper"
require "../../src/crystal_play/plugin_helpers/distribution_facts"

# Real Ansible reports a per-distro DISPLAY NAME for
# `ansible_distribution` - "Linux Mint Debian Edition" on LMDE, "Debian"
# on Raspbian - not the capitalized /etc/os-release ID this engine used
# to emit ("Linuxmint", "Raspbian"). A role gating on
# `ansible_distribution == "Linux Mint"`, or keying a vars file off it,
# took the wrong branch on every derivative.
#
# EVERY expectation below was GENERATED by running real Ansible's own
# `DistributionFiles.parse_distribution_file_Debian`
# (module_utils/facts/system/distribution.py, ansible-core 2.19.4) over
# the same fixture files in spec/fixtures/os_release/, not written by
# hand - so this is a differential against the real implementation
# rather than against someone's reading of it. That includes its quirks:
# Deepin's distribution_release really does run past the end of its own
# line (the release regexes use a negated character class with no
# MULTILINE anchor), and Cumulus's really is the whole VERSION= string.
#
# lmde7.txt is this workstation's own /etc/os-release, verbatim; the
# LMDE case is additionally verified end to end against a live
# `ansible-playbook` run on it - both engines print
# "dist=[Linux Mint Debian Edition] ... fam=[Debian]".
# {fixture, expected overrides (nil = no branch matched)}
private CASES = [
  {"cumulus.txt", {"ansible_distribution" => "Cumulus Linux", "ansible_distribution_major_version" => "4", "ansible_distribution_release" => "Cumulus Linux 4.4.2", "ansible_distribution_version" => "4.4.2"} of String => String},
  {"debian12.txt", {"ansible_distribution" => "Debian", "ansible_distribution_release" => "bookworm"} of String => String},
  {"deepin.txt", {"ansible_distribution" => "Deepin", "ansible_distribution_major_version" => "20", "ansible_distribution_release" => "apricot\nID=Deepin\nID_LIKE=debian\n", "ansible_distribution_version" => "20.9"} of String => String},
  {"devuan.txt", {"ansible_distribution" => "Devuan", "ansible_distribution_major_version" => "5", "ansible_distribution_release" => "daedalus", "ansible_distribution_version" => "5"} of String => String},
  {"kali.txt", {"ansible_distribution" => "Kali", "ansible_distribution_release" => "2023.3"} of String => String},
  {"lmde7.txt", {"ansible_distribution" => "Linux Mint Debian Edition"} of String => String},
  {"mint21.txt", {"ansible_distribution" => "Linux Mint", "ansible_distribution_major_version" => "21", "ansible_distribution_version" => "21.2"} of String => String},
  {"popos.txt", nil},
  {"raspbian.txt", {"ansible_distribution" => "Debian", "ansible_distribution_release" => "bullseye"} of String => String},
  {"steamos.txt", {"ansible_distribution" => "SteamOS"} of String => String},
  {"ubuntu2204.txt", {"ansible_distribution" => "Ubuntu"} of String => String},
]

describe CrystalPlay::PluginHelpers::DistributionFacts do
  describe ".refine_debian" do
    CASES.each do |(fixture, expected)|
      it "matches real Ansible's own parser for #{fixture}" do
        data = File.read(File.join(__DIR__, "..", "fixtures", "os_release", fixture))
        CrystalPlay::PluginHelpers::DistributionFacts.refine_debian(data).should eq(expected)
      end
    end
  end

  describe ".family_for" do
    it "maps every display name #refine_debian can produce to a family" do
      # A display name with no family entry would fall through to
      # ID_LIKE, or to the distribution name itself - the bug this pairs
      # with. Guards the two tables against drifting apart.
      CASES.each do |(_fixture, expected)|
        next unless expected
        name = expected["ansible_distribution"]
        CrystalPlay::PluginHelpers::DistributionFacts.family_for(name).should eq("Debian")
      end
    end

    it "still maps the mainstream RedHat-family names" do
      CrystalPlay::PluginHelpers::DistributionFacts.family_for("Rocky").should eq("RedHat")
      CrystalPlay::PluginHelpers::DistributionFacts.family_for("AlmaLinux").should eq("RedHat")
      CrystalPlay::PluginHelpers::DistributionFacts.family_for("CentOS").should eq("RedHat")
    end

    it "returns nil for a name it does not know, so the caller can fall back to ID_LIKE" do
      CrystalPlay::PluginHelpers::DistributionFacts.family_for("Nonesuch").should be_nil
    end
  end
end
