require "../spec_helper"
require "../../src/crystal_play/vault"

# This exact ciphertext was generated by real `ansible-vault encrypt`
# (password "vaultpassword", plaintext "hello vault world") inside the
# compat Docker image - not hand-crafted - and independently re-verified
# byte-for-byte with Python's hashlib/cryptography (PBKDF2-HMAC-SHA256 ->
# AES key/HMAC key/IV split, HMAC-SHA256 over the ciphertext, AES-256-CTR,
# PKCS7 unpad) before being used here. If this spec ever needs updating,
# regenerate it from real ansible-vault, don't hand-edit the hex.
private REAL_ANSIBLE_VAULT_FIXTURE = <<-VAULT
  $ANSIBLE_VAULT;1.1;AES256
  37666131613238313139643136313765613630336431623232353862656236613934323734313964
  3837333735353334303139623766613737366530633362630a633537646164356533343634353765
  65353138356132663164383437333231333231336137616465303638313662356238363334613463
  3032386130636663660a353433623236356233323965363566623135636238343439363036313331
  36303064303036643863656465303736363033316533336338373064393539373531
  VAULT

private REAL_ANSIBLE_VAULT_PASSWORD = "vaultpassword"

describe CrystalPlay::Vault do
  describe ".encrypted?" do
    it "recognizes the vault header" do
      CrystalPlay::Vault.encrypted?(REAL_ANSIBLE_VAULT_FIXTURE).should be_true
    end

    it "returns false for plain content" do
      CrystalPlay::Vault.encrypted?("- name: play\n  hosts: all\n").should be_false
    end
  end

  describe ".decrypt" do
    it "decrypts a real ansible-vault-encrypted fixture with the correct password" do
      CrystalPlay::Vault.decrypt(REAL_ANSIBLE_VAULT_FIXTURE, REAL_ANSIBLE_VAULT_PASSWORD).should eq("hello vault world")
    end

    it "raises with a clear message for the wrong password" do
      expect_raises(CrystalPlay::Vault::Error, /HMAC mismatch/) do
        CrystalPlay::Vault.decrypt(REAL_ANSIBLE_VAULT_FIXTURE, "wrong password")
      end
    end

    it "raises with a clear message for content without the vault header" do
      expect_raises(CrystalPlay::Vault::Error, /missing \$ANSIBLE_VAULT header/) do
        CrystalPlay::Vault.decrypt("not a vault file", REAL_ANSIBLE_VAULT_PASSWORD)
      end
    end

    it "raises with a clear message for an unsupported cipher" do
      expect_raises(CrystalPlay::Vault::Error, /Unsupported vault cipher/) do
        CrystalPlay::Vault.decrypt("$ANSIBLE_VAULT;1.1;AES256_OLD\ndeadbeef\n", REAL_ANSIBLE_VAULT_PASSWORD)
      end
    end
  end

  describe ".encrypt / .decrypt round trip" do
    it "decrypts what it just encrypted" do
      plaintext = "a secret value with spaces and\nnewlines\n"
      encrypted = CrystalPlay::Vault.encrypt(plaintext, "some password")

      CrystalPlay::Vault.encrypted?(encrypted).should be_true
      CrystalPlay::Vault.decrypt(encrypted, "some password").should eq(plaintext)
    end

    it "round-trips content that is an exact multiple of the AES block size (16 bytes)" do
      plaintext = "0123456789ABCDEF" # exactly 16 bytes
      encrypted = CrystalPlay::Vault.encrypt(plaintext, "pw")
      CrystalPlay::Vault.decrypt(encrypted, "pw").should eq(plaintext)
    end

    it "round-trips empty content" do
      encrypted = CrystalPlay::Vault.encrypt("", "pw")
      CrystalPlay::Vault.decrypt(encrypted, "pw").should eq("")
    end

    it "produces a header line matching the real ansible-vault format" do
      encrypted = CrystalPlay::Vault.encrypt("x", "pw")
      encrypted.lines.first.should eq("$ANSIBLE_VAULT;1.1;AES256")
    end

    it "wraps the hex body at 80 columns, matching real ansible-vault" do
      encrypted = CrystalPlay::Vault.encrypt("x" * 500, "pw")
      body_lines = encrypted.lines[1..-2] # drop header and trailing blank line from the final \n
      body_lines.each(&.size.should(be <= 80))
      body_lines[0..-2].each(&.size.should(eq(80))) # every line but the last is exactly full
    end

    it "fails to decrypt with a different password than it was encrypted with" do
      encrypted = CrystalPlay::Vault.encrypt("secret", "correct horse")
      expect_raises(CrystalPlay::Vault::Error, /HMAC mismatch/) do
        CrystalPlay::Vault.decrypt(encrypted, "battery staple")
      end
    end

    it "uses a fresh random salt each time, so encrypting the same plaintext twice differs" do
      first = CrystalPlay::Vault.encrypt("same plaintext", "pw")
      second = CrystalPlay::Vault.encrypt("same plaintext", "pw")
      first.should_not eq(second)
    end
  end

  describe ".maybe_decrypt_json" do
    it "decrypts a vault-encrypted string value" do
      CrystalPlay::Vault.password = "pw"
      encrypted = CrystalPlay::Vault.encrypt("secret value", "pw")
      result = CrystalPlay::Vault.maybe_decrypt_json(JSON::Any.new(encrypted))
      result.as_s.should eq("secret value")
    ensure
      CrystalPlay::Vault.password = nil
    end

    it "leaves plain string values untouched" do
      result = CrystalPlay::Vault.maybe_decrypt_json(JSON::Any.new("plain"))
      result.as_s.should eq("plain")
    end

    it "leaves non-string values untouched" do
      CrystalPlay::Vault.maybe_decrypt_json(JSON::Any.new(42_i64)).as_i64.should eq(42)
      CrystalPlay::Vault.maybe_decrypt_json(JSON::Any.new(true)).as_bool.should eq(true)
    end

    it "recurses into arrays" do
      CrystalPlay::Vault.password = "pw"
      encrypted = CrystalPlay::Vault.encrypt("nested secret", "pw")
      value = JSON::Any.new([JSON::Any.new("plain"), JSON::Any.new(encrypted)])
      result = CrystalPlay::Vault.maybe_decrypt_json(value)
      result.as_a.map(&.as_s).should eq(["plain", "nested secret"])
    ensure
      CrystalPlay::Vault.password = nil
    end

    it "recurses into hashes" do
      CrystalPlay::Vault.password = "pw"
      encrypted = CrystalPlay::Vault.encrypt("hash secret", "pw")
      value = JSON::Any.new({"plain" => JSON::Any.new("x"), "secret" => JSON::Any.new(encrypted)})
      result = CrystalPlay::Vault.maybe_decrypt_json(value)
      result.as_h["plain"].as_s.should eq("x")
      result.as_h["secret"].as_s.should eq("hash secret")
    ensure
      CrystalPlay::Vault.password = nil
    end

    # Since 0.9.583 an undecryptable value is left ENCRYPTED rather than
    # aborting: real Ansible defers the failure to the point of USE, so a
    # playbook carrying a vault var it never references runs fine with no
    # secret at all (verified against ansible-core 2.19.4: unused var and
    # no password exits 0; using it exits 2). The substitutor raises when
    # such a value is actually rendered.
    it "leaves a value encrypted when no password can decrypt it, rather than raising" do
      encrypted = CrystalPlay::Vault.encrypt("secret", "pw")
      CrystalPlay::Vault.maybe_decrypt_json(JSON::Any.new(encrypted)).as_s.should eq(encrypted)
    end

    it "raises only when such a value is rendered" do
      encrypted = CrystalPlay::Vault.encrypt("secret", "pw")
      vars = {"v" => CrystalPlay::Vault.maybe_decrypt_json(JSON::Any.new(encrypted))}
      substitutor = CrystalPlay::VarSubstitutor.new(vars: vars, host_name: "localhost")

      expect_raises(CrystalPlay::VarSubstitutor::UndecryptableVaultError, /undecryptable variable/) do
        substitutor.substitute("{{ v }}")
      end
    end
  end
end
