#!/usr/bin/env crystal

require "json"
require "../src/crystal_play/base_plugin"

lib LibC
  fun umask(mask : ModeT) : ModeT
end

module CrystalPlay
  # openssl_csr plugin (community.crypto.openssl_csr) - generates
  # certificate signing requests.
  #
  # Backed by the `openssl` CLI, like `openssl_privatekey.cr` and
  # `openssl_dhparam.cr` next to it. Behavior differentialed against the
  # real module (community.crypto 3.1.1 / ansible-core 2.19.4):
  #
  #   * with no explicit subject_alt_name, a common_name becomes a
  #     `DNS:<CN>` SAN (use_common_name_for_san, default true) - roles
  #     depend on this without knowing it, and a CSR missing it produces
  #     certificates modern clients reject outright
  #   * changing the subject, the SANs/usages, or the private key the
  #     CSR was made from regenerates it
  #   * changing only `digest:` does NOT regenerate (verified live) -
  #     the real module never compares it
  #   * the file is written with the process umask, NOT the 0600 that
  #     openssl_privatekey forces (a CSR is public information)
  #
  # Idempotency is decided by generating the CSR that WOULD be written
  # and comparing it against the existing one, rather than parsing every
  # field back out and comparing piecemeal: `openssl req -text`'s "Data"
  # block covers the subject, the public key and every extension with
  # its criticality, and deliberately stops short of the signature
  # (which for ECDSA keys is randomized, and whose algorithm line is
  # exactly the `digest:` the real module ignores).
  class OpensslCsrPlugin < BasePlugin
    # Emitted in this order to match the real module's own canonical
    # subject ordering (verified against a generated CSR: C, ST, L, O,
    # OU, CN, emailAddress), so a CSR generated by real Ansible and one
    # generated here compare equal instead of endlessly regenerating
    # each other.
    SUBJECT_FIELDS = [
      {"country_name", "C"},
      {"state_or_province_name", "ST"},
      {"locality_name", "L"},
      {"organization_name", "O"},
      {"organizational_unit_name", "OU"},
      {"common_name", "CN"},
      {"email_address", "emailAddress"},
    ]

    def execute : PluginResult
      path = @params["path"]?
      return failure("missing required arguments: path") unless path

      path = expand_tilde(path)
      state = @params["state"]? || "present"
      check_mode = is_true?(@params["check_mode"]?)

      return remove(path, check_mode) if state == "absent"

      privatekey_path = @params["privatekey_path"]?
      return failure("state is present but all of the following are missing: privatekey_path") unless privatekey_path
      privatekey_path = expand_tilde(privatekey_path)
      return failure("The private key #{privatekey_path} does not exist") unless File.exists?(privatekey_path)

      base_dir = File.dirname(path)
      return failure("The directory #{base_dir} does not exist or the file is not a directory") unless Dir.exists?(base_dir)

      candidate = secure_tempfile(path, "csr-candidate")
      begin
        if error = generate(candidate, privatekey_path)
          return failure(error)
        end

        changed = is_true?(@params["force"]?) || !File.exists?(path) || !equivalent?(path, candidate)

        if changed && !check_mode
          backup_file = backup(path)
          File.rename(candidate, path)
          # A CSR is not secret: with no explicit mode: the real module
          # leaves the umask to decide (0664 under the usual 0022), NOT
          # the 0600 openssl_privatekey forces - and the candidate file
          # was deliberately created 0600 while it briefly sat next to
          # the destination, so the umask default has to be reapplied
          # here rather than inherited from it.
          File.chmod(path, 0o666 & ~current_umask) unless @params["mode"]?
          apply_owner_group_mode(path, @params["owner"]?, @params["group"]?, @params["mode"]?)
          return result(true, path, privatekey_path, backup_file)
        end

        return result(true, path, privatekey_path, nil) if changed

        attrs_changed = apply_attrs(path)
        result(attrs_changed, path, privatekey_path, nil)
      ensure
        File.delete(candidate) if File.exists?(candidate)
      end
    end

    private def failure(msg : String) : PluginResult
      PluginResult.new(changed: false, failed: true, msg: msg)
    end

    private def remove(path : String, check_mode : Bool) : PluginResult
      exists = File.exists?(path)
      backup_file = nil
      if exists && !check_mode
        backup_file = backup(path)
        File.delete(path)
      end
      res = PluginResult.new(changed: exists, failed: false, msg: "")
      res.extra["filename"] = JSON::Any.new(path)
      res.extra["backup_file"] = JSON::Any.new(backup_file) if backup_file
      res
    end

    # --- desired state -------------------------------------------------

    private def subject_pairs : Array(Tuple(String, String))
      pairs = [] of Tuple(String, String)
      SUBJECT_FIELDS.each do |(param, short)|
        if value = @params[param]?
          pairs << {short, value} unless value.empty?
        end
      end

      # `subject:` is a free-form mapping of additional fields, appended
      # after the named ones exactly as the real module does.
      if raw = @params["subject"]?
        if parsed = (JSON.parse(raw).as_h? rescue nil)
          parsed.each do |key, value|
            pairs << {key, value.as_s? || value.to_s}
          end
        end
      end
      pairs
    end

    private def list_param(name : String) : Array(String)
      raw = @params[name]?
      return [] of String if raw.nil? || raw.empty?

      if parsed = (JSON.parse(raw).as_a? rescue nil)
        parsed.map { |v| v.as_s? || v.to_s }
      else
        raw.split(',').map(&.strip).reject(&.empty?)
      end
    end

    private def subject_alt_names : Array(String)
      names = list_param("subject_alt_name")
      return names unless names.empty?

      # use_common_name_for_san (default true): a CSR with a common name
      # and no SAN of its own gets `DNS:<CN>`.
      return names unless is_true?(@params["use_common_name_for_san"]?, default: true)
      if (cn = @params["common_name"]?) && !cn.empty?
        names << "DNS:#{cn}"
      end
      names
    end

    private def critical(name : String) : String
      is_true?(@params[name]?) ? "critical," : ""
    end

    private def generate(dest : String, privatekey_path : String) : String?
      digest = @params["digest"]? || "sha256"
      args = ["req", "-new", "-key", privatekey_path, "-out", dest, "-#{digest}"]

      if (passphrase = @params["privatekey_passphrase"]?) && !passphrase.empty?
        args.concat(["-passin", "pass:#{passphrase}"])
      end

      args.concat(["-subj", subject_argument])

      # Extension order matches the real module's own output (SAN, key
      # usage, extended key usage, basic constraints, then TLS feature),
      # which the "Data" block comparison is sensitive to.
      if (sans = subject_alt_names) && !sans.empty?
        args.concat(["-addext", "subjectAltName=#{critical("subject_alt_name_critical")}#{sans.join(",")}"])
      end
      if (usage = list_param("key_usage")) && !usage.empty?
        args.concat(["-addext", "keyUsage=#{critical("key_usage_critical")}#{usage.join(",")}"])
      end
      if (usage = list_param("extended_key_usage")) && !usage.empty?
        args.concat(["-addext", "extendedKeyUsage=#{critical("extended_key_usage_critical")}#{usage.join(",")}"])
      end
      if (constraints = list_param("basic_constraints")) && !constraints.empty?
        args.concat(["-addext", "basicConstraints=#{critical("basic_constraints_critical")}#{constraints.join(",")}"])
      end
      if is_true?(@params["ocsp_must_staple"]?)
        args.concat(["-addext", "tlsfeature=#{critical("ocsp_must_staple_critical")}status_request"])
      end

      run_openssl(args)
    end

    # OpenSSL's `-subj` uses `/` as the field separator, so any `/` in a
    # value (a common thing in an organization name) has to be escaped
    # or it silently splits the subject into extra fields.
    private def subject_argument : String
      String.build do |str|
        subject_pairs.each do |(key, value)|
          str << '/' << key << '=' << value.gsub("\\", "\\\\").gsub("/", "\\/")
        end
      end
    end

    # --- comparison ----------------------------------------------------

    # The "Data" block of `openssl req -text`: everything the real
    # module compares (subject, public key, extensions + criticality)
    # and nothing it ignores (the signature and its digest algorithm,
    # which live after this block).
    private def data_block(path : String) : String?
      stdout_io = IO::Memory.new
      err = IO::Memory.new
      status = Process.run("openssl", ["req", "-in", path, "-noout", "-text"], output: stdout_io, error: err)
      return nil unless status.success?

      lines = [] of String
      stdout_io.to_s.each_line do |line|
        break if line.starts_with?("    Signature Algorithm:") || line.starts_with?("    Signature Value")
        lines << line.rstrip
      end
      lines.join("\n")
    end

    private def equivalent?(existing : String, candidate : String) : Bool
      a = data_block(existing)
      b = data_block(candidate)
      return false unless a && b
      a == b
    end

    # --- reporting ------------------------------------------------------

    private def result(changed : Bool, path : String, privatekey_path : String,
                       backup_file : String?) : PluginResult
      res = PluginResult.new(changed: changed, failed: false, msg: "")
      res.extra["filename"] = JSON::Any.new(path)
      res.extra["privatekey"] = JSON::Any.new(privatekey_path)
      res.extra["subject"] = JSON::Any.new(subject_pairs.map { |(key, value)|
        JSON::Any.new([JSON::Any.new(key), JSON::Any.new(value)])
      })
      res.extra["subjectAltName"] = json_list(subject_alt_names)
      res.extra["keyUsage"] = json_list(list_param("key_usage"))
      res.extra["extendedKeyUsage"] = json_list(list_param("extended_key_usage"))
      res.extra["basicConstraints"] = json_list(list_param("basic_constraints"))
      res.extra["ocspMustStaple"] = JSON::Any.new(is_true?(@params["ocsp_must_staple"]?))
      res.extra["name_constraints_permitted"] = json_list(list_param("name_constraints_permitted"))
      res.extra["name_constraints_excluded"] = json_list(list_param("name_constraints_excluded"))
      res.extra["backup_file"] = JSON::Any.new(backup_file) if backup_file
      if is_true?(@params["return_content"]?) && File.exists?(path)
        res.extra["csr"] = JSON::Any.new(File.read(path))
      end
      res
    end

    private def json_list(values : Array(String)) : JSON::Any
      JSON::Any.new(values.map { |v| JSON::Any.new(v) })
    end

    private def apply_attrs(path : String) : Bool
      return false unless File.exists?(path)
      before = File.info(path).permissions.value
      apply_owner_group_mode(path, @params["owner"]?, @params["group"]?, @params["mode"]?)
      File.info(path).permissions.value != before
    rescue
      false
    end

    private def run_openssl(args : Array(String)) : String?
      stdout_io = IO::Memory.new
      err = IO::Memory.new
      status = Process.run("openssl", args, output: stdout_io, error: err)
      return nil if status.success?
      "openssl req failed: #{err.to_s.strip}"
    end

    # Written next to the destination so the install step is a rename
    # within one filesystem (see openssl_privatekey.cr's own note).
    private def current_umask : UInt32
      mask = LibC.umask(0o022_u32)
      LibC.umask(mask)
      mask.to_u32
    end

    private def secure_tempfile(near : String, prefix : String) : String
      path = File.tempname(prefix, dir: File.dirname(near))
      File.write(path, "")
      File.chmod(path, 0o600)
      path
    end

    private def backup(path : String) : String?
      return nil unless is_true?(@params["backup"]?)
      return nil unless File.exists?(path)
      dest = "#{path}.#{Process.pid}.#{Time.local.to_s("%Y-%m-%d@%H:%M:%S")}~"
      File.copy(path, dest)
      dest
    end
  end
end

# Plugin entry point
input = STDIN.gets_to_end
config = JSON.parse(input)

plugin = CrystalPlay::OpensslCsrPlugin.new(config)
plugin.run
