require "../spec_helper"
require "file_utils"

# community.crypto.openssl_csr, differentialed against the real module
# (community.crypto 3.1.1 / ansible-core 2.19.4). The cross-engine
# checks matter most here: a CSR generated by real Ansible must not be
# regenerated by this one and vice versa, which is what roles hit on
# their second run.
private TMP_DIR = File.join(PluginSpecHelper::PROJECT_ROOT, "spec", "tmp", "openssl_csr")
private KEY     = File.join(TMP_DIR, "a.key")

Spec.before_suite do
  FileUtils.rm_rf(TMP_DIR) if Dir.exists?(TMP_DIR)
  Dir.mkdir_p(TMP_DIR)
  PluginSpecHelper.run("openssl_privatekey", {"path" => KEY, "size" => "2048"})
end

private def csr_path(name : String) : String
  File.join(TMP_DIR, name)
end

private def csr_text(path : String) : String
  `openssl req -in #{path} -noout -text 2>/dev/null`
end

# Subject one-line output format drifts across OpenSSL versions (3.0
# prints "CN = example.com", 3.5 prints "CN=example.com"), so the
# assertions normalize to the no-space form before comparing.
private def subject_line(path : String) : String
  `openssl req -in #{path} -noout -subject 2>/dev/null`.strip.gsub(" = ", "=")
end

describe "openssl_csr plugin" do
  it "generates a CSR carrying the requested subject" do
    path = csr_path("a.csr")
    result = PluginSpecHelper.run("openssl_csr",
      {"path" => path, "privatekey_path" => KEY, "common_name" => "example.com"})

    result["changed"].as_bool.should be_true
    result["filename"].as_s.should eq(path)
    result["privatekey"].as_s.should eq(KEY)
    subject_line(path).should eq("subject=CN=example.com")
  end

  # The single most consequential default in this module: without it the
  # issued certificate has no SAN at all, and every modern client
  # rejects it.
  it "adds the common name as a DNS SAN by default" do
    csr_text(csr_path("a.csr")).should contain("DNS:example.com")
  end

  it "honours use_common_name_for_san: false" do
    path = csr_path("nosan.csr")
    PluginSpecHelper.run("openssl_csr",
      {"path" => path, "privatekey_path" => KEY, "common_name" => "example.com",
       "use_common_name_for_san" => "false"})

    csr_text(path).should_not contain("Subject Alternative Name")
  end

  it "is idempotent for an unchanged request" do
    path = csr_path("a.csr")
    before = File.read(path)
    result = PluginSpecHelper.run("openssl_csr",
      {"path" => path, "privatekey_path" => KEY, "common_name" => "example.com"})

    result["changed"].as_bool.should be_false
    File.read(path).should eq(before)
  end

  it "regenerates when the subject changes" do
    path = csr_path("a.csr")
    result = PluginSpecHelper.run("openssl_csr",
      {"path" => path, "privatekey_path" => KEY, "common_name" => "other.com"})

    result["changed"].as_bool.should be_true
    subject_line(path).should eq("subject=CN=other.com")
  end

  it "regenerates when the private key changes" do
    path = csr_path("a.csr")
    other_key = File.join(TMP_DIR, "other.key")
    PluginSpecHelper.run("openssl_privatekey", {"path" => other_key, "size" => "2048"})

    result = PluginSpecHelper.run("openssl_csr",
      {"path" => path, "privatekey_path" => other_key, "common_name" => "other.com"})
    result["changed"].as_bool.should be_true
  end

  # Verified live: the real module never compares the digest, so a
  # changed digest: alone must NOT reissue.
  it "does not regenerate for a digest change alone" do
    path = csr_path("digest.csr")
    PluginSpecHelper.run("openssl_csr",
      {"path" => path, "privatekey_path" => KEY, "common_name" => "digest.com", "digest" => "sha512"})

    result = PluginSpecHelper.run("openssl_csr",
      {"path" => path, "privatekey_path" => KEY, "common_name" => "digest.com", "digest" => "sha256"})
    result["changed"].as_bool.should be_false
  end

  it "writes the full subject in the real module's canonical field order" do
    path = csr_path("full.csr")
    PluginSpecHelper.run("openssl_csr", {
      "path"                     => path,
      "privatekey_path"          => KEY,
      "common_name"              => "full.example.com",
      "country_name"             => "NL",
      "state_or_province_name"   => "Noord-Holland",
      "locality_name"            => "Amsterdam",
      "organization_name"        => "Acme",
      "organizational_unit_name" => "IT",
      "email_address"            => "admin@example.com",
    })

    subject_line(path).should eq(
      "subject=C=NL, ST=Noord-Holland, L=Amsterdam, O=Acme, OU=IT, CN=full.example.com, emailAddress=admin@example.com")
  end

  it "writes SAN, key usage, extended key usage and basic constraints with their criticality" do
    path = csr_path("ext.csr")
    result = PluginSpecHelper.run("openssl_csr", {
      "path"                       => path,
      "privatekey_path"            => KEY,
      "common_name"                => "san.example.com",
      "subject_alt_name"           => %(["DNS:san.example.com","DNS:www.example.com","IP:10.0.0.1"]),
      "key_usage"                  => %(["digitalSignature","keyEncipherment"]),
      "extended_key_usage"         => %(["serverAuth"]),
      "basic_constraints"          => %(["CA:FALSE"]),
      "basic_constraints_critical" => "true",
    })

    result["subjectAltName"].as_a.map(&.as_s).should eq(["DNS:san.example.com", "DNS:www.example.com", "IP:10.0.0.1"])
    result["keyUsage"].as_a.map(&.as_s).should eq(["digitalSignature", "keyEncipherment"])

    text = csr_text(path)
    text.should contain("DNS:san.example.com, DNS:www.example.com, IP Address:10.0.0.1")
    text.should contain("Digital Signature, Key Encipherment")
    text.should contain("TLS Web Server Authentication")
    text.should contain("X509v3 Basic Constraints: critical")

    rerun = PluginSpecHelper.run("openssl_csr", {
      "path"                       => path,
      "privatekey_path"            => KEY,
      "common_name"                => "san.example.com",
      "subject_alt_name"           => %(["DNS:san.example.com","DNS:www.example.com","IP:10.0.0.1"]),
      "key_usage"                  => %(["digitalSignature","keyEncipherment"]),
      "extended_key_usage"         => %(["serverAuth"]),
      "basic_constraints"          => %(["CA:FALSE"]),
      "basic_constraints_critical" => "true",
    })
    rerun["changed"].as_bool.should be_false
  end

  it "regenerates when only the criticality of an extension changes" do
    path = csr_path("ext.csr")
    result = PluginSpecHelper.run("openssl_csr", {
      "path"                       => path,
      "privatekey_path"            => KEY,
      "common_name"                => "san.example.com",
      "subject_alt_name"           => %(["DNS:san.example.com","DNS:www.example.com","IP:10.0.0.1"]),
      "key_usage"                  => %(["digitalSignature","keyEncipherment"]),
      "extended_key_usage"         => %(["serverAuth"]),
      "basic_constraints"          => %(["CA:FALSE"]),
      "basic_constraints_critical" => "false",
    })

    result["changed"].as_bool.should be_true
    csr_text(path).should_not contain("X509v3 Basic Constraints: critical")
  end

  # A CSR is public information: unlike a private key it is NOT forced
  # to 0600, it gets the umask default.
  it "leaves permissions to the umask unless mode is given" do
    path = csr_path("perm.csr")
    PluginSpecHelper.run("openssl_csr",
      {"path" => path, "privatekey_path" => KEY, "common_name" => "perm.example.com"})

    umask = `umask`.strip.to_i(8)
    File.info(path).permissions.value.should eq(0o666 & ~umask)

    PluginSpecHelper.run("openssl_csr",
      {"path" => path, "privatekey_path" => KEY, "common_name" => "perm.example.com", "mode" => "0640"})
    File.info(path).permissions.value.should eq(0o640)
  end

  it "escapes a slash in a subject value instead of splitting the field" do
    path = csr_path("slash.csr")
    PluginSpecHelper.run("openssl_csr",
      {"path" => path, "privatekey_path" => KEY, "common_name" => "slash.example.com",
       "organization_name" => "Acme/Roadrunner"})

    subject_line(path).should contain("O=Acme/Roadrunner")
  end

  it "returns the CSR content only when asked, and removes it for state: absent" do
    path = csr_path("content.csr")
    plain = PluginSpecHelper.run("openssl_csr",
      {"path" => path, "privatekey_path" => KEY, "common_name" => "content.example.com"})
    plain["csr"]?.should be_nil

    result = PluginSpecHelper.run("openssl_csr",
      {"path" => path, "privatekey_path" => KEY, "common_name" => "content.example.com",
       "return_content" => "true"})
    result["csr"].as_s.should start_with("-----BEGIN CERTIFICATE REQUEST-----")

    removed = PluginSpecHelper.run("openssl_csr", {"path" => path, "state" => "absent"})
    removed["changed"].as_bool.should be_true
    File.exists?(path).should be_false
    PluginSpecHelper.run("openssl_csr", {"path" => path, "state" => "absent"})["changed"].as_bool.should be_false
  end

  it "fails when the private key does not exist" do
    result = PluginSpecHelper.run("openssl_csr",
      {"path" => csr_path("missing.csr"), "privatekey_path" => File.join(TMP_DIR, "nope.key"),
       "common_name" => "x.example.com"})

    result["failed"].as_bool.should be_true
    result["msg"].as_s.should contain("does not exist")
  end
end
