require "../minitest_helper"
require "../../src/krikri/plugin_helpers/mysql_salted_hash"

# mysql_user's `salt:` support makes the caching_sha2_password /
# sha256_password storage hash DETERMINISTIC - ansible.mysql 5.2.0's
# user.py compares mysql.user.authentication_string against
# mysql_sha256_password_hash(plugin_auth_string, salt) before deciding
# whether an ALTER is needed, and issues `IDENTIFIED WITH <plugin> AS
# 0x<hash_hex>` when one is. Without it, the server's own random-salt
# hash never equals the plaintext the task asked to store, so every
# warm run reported changed where ansible-playbook reported ok
# (wiggels.snipeit's "Create snipeit user", round 1500042).
#
# Every expected value below was generated by running ansible.mysql's
# OWN Python implementation (plugins/module_utils/implementations/mysql/
# hash.py) - the port is pinned to its bytes, not re-derived here.
describe Krikri::PluginHelpers::MysqlSaltedHash do
  it "matches the Python implementation's raw storage hash" do
    Krikri::PluginHelpers::MysqlSaltedHash.hash("snipe-secret-pw", "01234567890123456789")
      .must_equal("$A$005$012345678901234567897H9WpSKb516VwPriSE83WmYfDriJ9/J04u.1iCTZk.4")
    Krikri::PluginHelpers::MysqlSaltedHash.hash("a", "abcdefghijklmnopqrst")
      .must_equal("$A$005$abcdefghijklmnopqrstGUZJvjAnfV4uuLEV1GxNc1ckneuAhZFlcwg6YjZ.C.7")
  end

  it "handles the empty-password edge the Python port covers" do
    Krikri::PluginHelpers::MysqlSaltedHash.hash("", "00000000000000000000")
      .must_equal("$A$005$000000000000000000008tgUDTe7VG9ez85C7LPK1sCls24uGtF9AS.aoCURT99")
  end

  it "handles a long password whose key stream spans multiple digest blocks" do
    Krikri::PluginHelpers::MysqlSaltedHash.hash("caching_sha2_password-test password 123!", "saltysaltysaltysalty")
      .must_equal("$A$005$saltysaltysaltysaltyuVmc6E6epyTLe9rX4fjjYk71W./5giXOwVmiBUs7Vk4")
  end

  it "hexes the raw hash the way the AS 0x... statement needs it" do
    Krikri::PluginHelpers::MysqlSaltedHash.hash_hex("snipe-secret-pw", "01234567890123456789")
      .must_equal("2441243030352430313233343536373839303132333435363738393748395770534B62353136567750726953453833576D59664472694A392F4A3034752E316943545A6B2E34")
  end
end
