require "../minitest_helper"
require "../../src/krikri/vault"

# This exact ciphertext was generated by `Ansible-vault encrypt`
# (password "vaultpassword", plaintext "hello vault world") inside the
# compat Docker image - not hand-crafted - and independently re-verified
# byte-for-byte with Python's hashlib/cryptography (PBKDF2-HMAC-SHA256 ->
# AES key/HMAC key/IV split, HMAC-SHA256 over the ciphertext, AES-256-CTR,
# PKCS7 unpad) before being used here. If this spec ever needs updating,
# regenerate it from Ansible-vault, don't hand-edit the hex.
private REAL_ANSIBLE_VAULT_FIXTURE = <<-VAULT
  $ANSIBLE_VAULT;1.1;AES256
  37666131613238313139643136313765613630336431623232353862656236613934323734313964
  3837333735353334303139623766613737366530633362630a633537646164356533343634353765
  65353138356132663164383437333231333231336137616465303638313662356238363334613463
  3032386130636663660a353433623236356233323965363566623135636238343439363036313331
  36303064303036643863656465303736363033316533336338373064393539373531
  VAULT

private REAL_ANSIBLE_VAULT_PASSWORD = "vaultpassword"

describe Krikri::Vault do
  include RaisesAssertion
  describe ".encrypted?" do
    include RaisesAssertion
    it "recognizes the vault header" do
      with_vault do
        Krikri::Vault.encrypted?(REAL_ANSIBLE_VAULT_FIXTURE).must_equal(true)
      end
    end

    it "returns false for plain content" do
      with_vault do
        Krikri::Vault.encrypted?("- name: play\n  hosts: all\n").must_equal(false)
      end
    end
  end

  describe ".decrypt" do
    include RaisesAssertion
    it "decrypts a Ansible-vault-encrypted fixture with the correct password" do
      with_vault do
        Krikri::Vault.decrypt(REAL_ANSIBLE_VAULT_FIXTURE, REAL_ANSIBLE_VAULT_PASSWORD).must_equal("hello vault world")
      end
    end

    it "raises with a clear message for the wrong password" do
      with_vault do
        assert_raises_message(Krikri::Vault::Error, /HMAC mismatch/) do
          Krikri::Vault.decrypt(REAL_ANSIBLE_VAULT_FIXTURE, "wrong password")
        end
      end
    end

    it "raises with a clear message for content without the vault header" do
      with_vault do
        assert_raises_message(Krikri::Vault::Error, /missing \$ANSIBLE_VAULT header/) do
          Krikri::Vault.decrypt("not a vault file", REAL_ANSIBLE_VAULT_PASSWORD)
        end
      end
    end

    it "raises with a clear message for an unsupported cipher" do
      with_vault do
        assert_raises_message(Krikri::Vault::Error, /Unsupported vault cipher/) do
          Krikri::Vault.decrypt("$ANSIBLE_VAULT;1.1;AES256_OLD\ndeadbeef\n", REAL_ANSIBLE_VAULT_PASSWORD)
        end
      end
    end
  end

  describe ".encrypt / .decrypt round trip" do
    include RaisesAssertion
    it "decrypts what it just encrypted" do
      with_vault do
        plaintext = "a secret value with spaces and\nnewlines\n"
        encrypted = Krikri::Vault.encrypt(plaintext, "some password")

        Krikri::Vault.encrypted?(encrypted).must_equal(true)
        Krikri::Vault.decrypt(encrypted, "some password").must_equal(plaintext)
      end
    end

    it "round-trips content that is an exact multiple of the AES block size (16 bytes)" do
      with_vault do
        plaintext = "0123456789ABCDEF" # exactly 16 bytes
        encrypted = Krikri::Vault.encrypt(plaintext, "pw")
        Krikri::Vault.decrypt(encrypted, "pw").must_equal(plaintext)
      end
    end

    it "round-trips empty content" do
      with_vault do
        encrypted = Krikri::Vault.encrypt("", "pw")
        Krikri::Vault.decrypt(encrypted, "pw").must_equal("")
      end
    end

    it "produces a header line matching the Ansible-vault format" do
      with_vault do
        encrypted = Krikri::Vault.encrypt("x", "pw")
        encrypted.lines.first.must_equal("$ANSIBLE_VAULT;1.1;AES256")
      end
    end

    it "wraps the hex body at 80 columns, matching Ansible-vault" do
      with_vault do
        encrypted = Krikri::Vault.encrypt("x" * 500, "pw")
        body_lines = encrypted.lines[1..-2] # drop header and trailing blank line from the final \n
        body_lines.each { |line| (line.size <= 80).must_equal(true) }
        body_lines[0..-2].each { |line| line.size.must_equal(80) } # every line but the last is exactly full
      end
    end

    it "fails to decrypt with a different password than it was encrypted with" do
      with_vault do
        encrypted = Krikri::Vault.encrypt("secret", "correct horse")
        assert_raises_message(Krikri::Vault::Error, /HMAC mismatch/) do
          Krikri::Vault.decrypt(encrypted, "battery staple")
        end
      end
    end

    it "uses a fresh random salt each time, so encrypting the same plaintext twice differs" do
      with_vault do
        first = Krikri::Vault.encrypt("same plaintext", "pw")
        second = Krikri::Vault.encrypt("same plaintext", "pw")
        first.wont_equal(second)
      end
    end
  end

  describe ".maybe_decrypt_json" do
    include RaisesAssertion
    it "decrypts a vault-encrypted string value" do
      with_vault do
        Krikri::Vault.password = "pw"
        encrypted = Krikri::Vault.encrypt("secret value", "pw")
        result = Krikri::Vault.maybe_decrypt_json(JSON::Any.new(encrypted))
        result.as_s.must_equal("secret value")
      ensure
        Krikri::Vault.password = nil
      end
    end

    it "leaves plain string values untouched" do
      with_vault do
        result = Krikri::Vault.maybe_decrypt_json(JSON::Any.new("plain"))
        result.as_s.must_equal("plain")
      end
    end

    it "leaves non-string values untouched" do
      with_vault do
        Krikri::Vault.maybe_decrypt_json(JSON::Any.new(42_i64)).as_i64.must_equal(42)
        Krikri::Vault.maybe_decrypt_json(JSON::Any.new(true)).as_bool.must_equal(true)
      end
    end

    it "recurses into arrays" do
      with_vault do
        Krikri::Vault.password = "pw"
        encrypted = Krikri::Vault.encrypt("nested secret", "pw")
        value = JSON::Any.new([JSON::Any.new("plain"), JSON::Any.new(encrypted)])
        result = Krikri::Vault.maybe_decrypt_json(value)
        result.as_a.map(&.as_s).must_equal(["plain", "nested secret"])
      ensure
        Krikri::Vault.password = nil
      end
    end

    it "recurses into hashes" do
      with_vault do
        Krikri::Vault.password = "pw"
        encrypted = Krikri::Vault.encrypt("hash secret", "pw")
        value = JSON::Any.new({"plain" => JSON::Any.new("x"), "secret" => JSON::Any.new(encrypted)})
        result = Krikri::Vault.maybe_decrypt_json(value)
        result.as_h["plain"].as_s.must_equal("x")
        result.as_h["secret"].as_s.must_equal("hash secret")
      ensure
        Krikri::Vault.password = nil
      end
    end

    # Since 0.9.583 an undecryptable value is left ENCRYPTED rather than
    # aborting: Ansible defers the failure to the point of USE, so a
    # playbook carrying a vault var it never references runs fine with no
    # secret at all (verified against ansible-core 2.19.4: unused var and
    # no password exits 0; using it exits 2). The substitutor raises when
    # such a value is actually rendered.
    it "leaves a value encrypted when no password can decrypt it, rather than raising" do
      with_vault do
        encrypted = Krikri::Vault.encrypt("secret", "pw")
        Krikri::Vault.maybe_decrypt_json(JSON::Any.new(encrypted)).as_s.must_equal(encrypted)
      end
    end

    it "raises only when such a value is rendered" do
      with_vault do
        encrypted = Krikri::Vault.encrypt("secret", "pw")
        vars = {"v" => Krikri::Vault.maybe_decrypt_json(JSON::Any.new(encrypted))}
        substitutor = Krikri::VarSubstitutor.new(vars: vars, host_name: "localhost")

        assert_raises_message(Krikri::VarSubstitutor::UndecryptableVaultError, /undecryptable variable/) do
          substitutor.substitute("{{ v }}")
        end
      end
    end
  end
end
